-- ========================================
-- Check what tables exist
-- ========================================
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('daily_tips', 'reminders', 'forum_posts', 'profiles', 'focus_sessions', 'milestones');

-- ========================================
-- Create daily_tips table if it doesn't exist
-- ========================================
CREATE TABLE IF NOT EXISTS daily_tips (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  content text NOT NULL,
  category text DEFAULT 'general',
  is_active boolean DEFAULT true,
  created_by uuid REFERENCES profiles(id),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- If table exists but missing title column, add it
ALTER TABLE daily_tips ADD COLUMN IF NOT EXISTS title text NOT NULL DEFAULT '';

-- Enable RLS
ALTER TABLE daily_tips ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Everyone can view active tips" ON daily_tips;
DROP POLICY IF EXISTS "Admins can manage tips" ON daily_tips;

-- Create policies
CREATE POLICY "Everyone can view active tips"
  ON daily_tips FOR SELECT
  USING (is_active = true);

CREATE POLICY "Admins can manage tips"
  ON daily_tips FOR ALL
  TO authenticated
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role = 'admin'
    )
  )
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role = 'admin'
    )
  );

-- ========================================
-- Create reminders table if it doesn't exist
-- ========================================
CREATE TABLE IF NOT EXISTS reminders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  message text,
  category text DEFAULT 'general',
  remind_at timestamp with time zone NOT NULL,
  recurrence_pattern text,
  is_global boolean DEFAULT false,
  created_by uuid REFERENCES profiles(id),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Users can view their own reminders and global reminders" ON reminders;
DROP POLICY IF EXISTS "Admins can manage all reminders" ON reminders;

-- Create policies
CREATE POLICY "Users can view their own reminders and global reminders"
  ON reminders FOR SELECT
  TO authenticated
  USING (is_global = true OR created_by = auth.uid());

CREATE POLICY "Admins can manage all reminders"
  ON reminders FOR ALL
  TO authenticated
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role = 'admin'
    )
  )
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role = 'admin'
    )
  );

-- ========================================
-- Create forum_posts table if it doesn't exist
-- ========================================
CREATE TABLE IF NOT EXISTS forum_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  category text DEFAULT 'general',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE forum_posts ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Everyone can view posts" ON forum_posts;
DROP POLICY IF EXISTS "Users can create posts" ON forum_posts;
DROP POLICY IF EXISTS "Users can update own posts" ON forum_posts;
DROP POLICY IF EXISTS "Users can delete own posts" ON forum_posts;
DROP POLICY IF EXISTS "Admins can delete any post" ON forum_posts;

-- Create policies
CREATE POLICY "Everyone can view posts"
  ON forum_posts FOR SELECT
  USING (true);

CREATE POLICY "Users can create posts"
  ON forum_posts FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own posts"
  ON forum_posts FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own posts"
  ON forum_posts FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can delete any post"
  ON forum_posts FOR DELETE
  TO authenticated
  USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role = 'admin'
    )
  );

-- ========================================
-- Verify tables were created
-- ========================================
SELECT 
  table_name, 
  (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public' 
AND table_name IN ('daily_tips', 'reminders', 'forum_posts')
ORDER BY table_name;

